clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next

workspace:
  base: /test
  path: qa-automation

matrix:
  COMPOSER_BOUNDARY:
    - lowest
    - highest

pipeline:
  composer-install:
    group: init
    image: registry.fpfis.eu/fpfis/httpd-php:8.1-ci
    commands:
      - composer self-update --2
      - composer install --ansi --no-suggest --no-progress
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  composer-install-lowest:
    group: init
    image: registry.fpfis.eu/fpfis/httpd-php:8.1-ci
    commands:
      - composer self-update --2
      - composer update --prefer-${COMPOSER_BOUNDARY=lowest} --prefer-stable --ansi --no-suggest --no-progress
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  phpcs:
    image: registry.fpfis.eu/fpfis/httpd-php:8.1-ci
    commands:
      - ./vendor/bin/phpcs -p
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  phpunit:
    image: registry.fpfis.eu/fpfis/httpd-php:8.1-ci
    commands:
      - ./vendor/bin/phpunit
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
