workspace:
  base: /test
  path: qa-automation

matrix:
  PHP_VERSION:
    - 7.3
    - 7.4

pipeline:
  composer:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    commands:
      - composer self-update --1
      - composer install --no-suggest
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  phpcs:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    commands:
      - ./bin/phpcs

  phpunit:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    commands:
      - ./bin/phpunit phpcs/
