clone:
  git:
    image: plugins/git:next

workspace:
  base: /test
  path: qa-automation

matrix:
  COMPOSER_VERSION:
    - 1
    - 2
  COMPOSER_BOUNDARY:
    - lowest
    - highest
  PHP_VERSION:
    - 7.3
    - 7.4

pipeline:
  composer-install:
    group: init
    image: fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    commands:
      - composer --version
      - composer self-update --${COMPOSER_VERSION=1}
      - composer --version
      - composer install --ansi --no-suggest --no-progress
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  composer-install-lowest:
    group: init
    image: fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    commands:
      - composer --version
      - composer self-update --${COMPOSER_VERSION=1}
      - composer --version
      - composer install --ansi --no-suggest --no-progress
      - composer update --prefer-${COMPOSER_BOUNDARY=lowest} --prefer-stable --ansi --no-suggest --no-progress
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  grumphp:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/grumphp run
