clone:
  git:
    image: plugins/git:next

workspace:
  base: /test
  path: qa-automation

matrix:
  PHP_VERSION:
    - 7.2
    - 7.3

services:
  web:
    image: fpfis/httpd-php-dev:${PHP_VERSION=7.1}
    environment:
      - DOCUMENT_ROOT=/test/qa-automation

pipeline:
  composer:
    image: fpfis/httpd-php-dev:${PHP_VERSION=7.1}
    commands:
      - composer install --no-suggest
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
  phpcs:
    image: fpfis/httpd-php-dev:${PHP_VERSION=7.1}
    commands:
      - ./vendor/bin/phpcs -p
  phpunit:
    image: fpfis/httpd-php-dev:${PHP_VERSION=7.1}
    commands:
      - ./vendor/bin/phpunit phpcs/
